### ISSUE TITLE
Failed to fetch при sudo apt install [Linux]

### ISSUE THREAD

**Issue by bigwitch3r** [rnv812/DevOpsExamples#1]
Во время выполнения лабораторной работы нам необходимо создать виртуальное окружение:
`python3 -m venv venv`

Если у вас нет модуля venv и вам приходится устанавливать его командой `sudo apt install python3.10-venv` (для примера), есть шанс получить такую ошибку:

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.10/python3.10-venv_3.10.6-1%7e22.04.2_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Решается с помощью `sudo apt-get update`

Просьба добавить инфу об этом в методичку

**Comment by rnv812** [comment]
`venv` входит в стандартную библиотеку python3. Что вы понимаете под его отсутствием? Какая ошибка возникает при создании окружения?

**Comment by bigwitch3r** [comment]
Под его отсутствием я подразумеваю выдачу вот такой ошибки:
![image](https://user-images.githubusercontent.com/65015830/229777070-c79c04d8-f7a5-41a3-9ad6-f160c93bd20f.png)

**Comment by rnv812** [comment]
Хорошо, спасибо. Добавлю этот момент.
