### ISSUE TITLE
Авторизация в GitHub через терминал [Linux]

### ISSUE THREAD

**Issue by bigwitch3r** [rnv812/DevOpsExamples#2]
Если перед попыткой выполнения `git push` не была выполнена авторизация в GitHub, терминал запросит логин и пароль от аккаунта. Если ввести даже корректные данные, получим ошибку:

remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/bigwitch3r/DevOps_Lab2.git/'

Ошибка вызвана тем, что с 13 августа 2021 года GitHub отключил авторизацию по логину-паролю, в связи с чем необходимо сгенерировать токен на странице https://github.com/settings/tokens. Для избежания проблем лучше генерировать классический токен, как на скриншоте ниже.
![image](https://user-images.githubusercontent.com/65015830/229774567-caf404f4-e973-4ddd-95ec-4ad79f011f6d.png)

В поле Note вводим название токена, чтобы было проще определить, для чего мы его создавали. В списке Expiration выбираем период, в течение которого будет активен токен.

Далее необходимо выбрать, к каким возможностям GitHub токен будет иметь доступ. Здесь уже точно не скажу, что именно надо выбрать, но я выбрал всё сразу. В конце страницы нажимаем Generate token и копируем его. Не закрывайте страницу с токеном, пока не авторизуетесь в terminal.

**РЕШЕНИЕ:** авторизация через токен.
**КАК СДЕЛАТЬ:**

1. Переходим через терминал в директорию проекта.
2. Вводим команду `git remote set-url origin https://bigwitch3r:ТОКЕН@github.com/bigwitch3r/DevOps_Lab2.git`

Вместо bigwitch3r введите свой логин GitHub, вместо ТОКЕН - полностью скопированный токен. После символа "@" идёт ссылка на ваш GitHub-репозиторий, начиная с github.com.

Готово! Можно выполнять `git push`.

Просьба добавить в методичку.

**Comment by rnv812** [comment]
Жду pull request :)
